# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - qtbase5-dev
    - libxkbcommon-x11-0
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-randr0
    - libxcb-render-util0
    - libxcb-xinerama0
    - xvfb
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    post_install:
      - cd doc
      - ls
      # default readthedocs commans prefixed with xvfb-run
      - xvfb-run python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - htmlzip

python:
  install:
    - method: pip
      path: .
      extra_requirements:
          - all
          - doc
