language: python

env:
  global:
    - DISPLAY=99.0
    - DEPS="hyperspy-gui-traitsui qtpy pyqode.python"
    - TEST_DEPS="pytest pytest-qt"

dist: xenial
sudo: false

services:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services-xvfb
  - xvfb

matrix:
  include:
  - env: export PYTHON=3.7
  - env: export PYTHON=3.6
  - env: export PYTHON=3.5
  - env: export PYTHON=3.7
    os: osx
    language: generic
  - env: export PYTHON=3.6
    os: osx
    language: generic
    if: tag IS present
  - env: export PYTHON=3.5
    os: osx
    language: generic
    if: tag IS present

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then
      curl "https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh" -o miniconda.sh;
    else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh;
    ./miniconda.sh -b -p $HOME/miniconda;
    hash -r;

install:
  - source $HOME/miniconda/bin/activate root;
  - conda update -yq conda
  - conda create -n testenv --yes python=$PYTHON;
    source activate testenv;
    conda install -y -c conda-forge $DEPS $TEST_DEPS;
  - pip install -e .

script:
  - python -c 'import matplotlib.pyplot as plt; print(plt.get_backend())';
  - pytest;
