name: test_env
channels:
- defaults
- conda-forge
dependencies:
# Minimal dependencies
- autopep8
- hyperspy-base
- hyperspy-gui-traitsui
- matplotlib
- pyface
- pyqode.python
- pyqt
- qtconsole
- qtpy
- traits
- traitsui



