name: Documentation

on: [push, pull_request]

jobs:
  build_doc:
    permissions:
      contents: write
    name: Build doc
    runs-on: ubuntu-latest
    env:
      DISPLAY: :0
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.8

      - name: 'Install Ubuntu packages for Qt'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install qtbase5-dev
          sudo apt-get install libxkbcommon-x11-0
          sudo apt-get install libxcb-icccm4
          sudo apt-get install libxcb-image0
          sudo apt-get install libxcb-keysyms1
          sudo apt-get install libxcb-randr0
          sudo apt-get install libxcb-render-util0
          sudo apt-get install libxcb-xinerama0

      - name: Install Dependencies
        run: |
          pip install PyQt5 PyQtWebEngine

      - name: Install
        run: |
          pip install -e .[build-doc]

      - name: Build doc
        run: |
          sudo apt-get install xvfb
          cd doc
          xvfb-run make html

      - uses: actions/upload-artifact@v2
        with:
          path: ./doc/build/*

      - uses: peaceiris/actions-gh-pages@e1448a73ca97cd0b1a6f894340080366c5e8509a
        if: startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/html
