name: Documentation

on: [push, pull_request]


jobs:
  Build:
    # Use the "reusable workflow" from the hyperspy organisation
    uses: hyperspy/.github/.github/workflows/doc.yml@main
    with:
      doc_path: ./doc
      doc_build_path: ./doc/_build/html/
      pip_extra_doc: all,doc
      install_package_ubuntu: qtbase5-dev libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0

  Push:
    needs: Build
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'hyperspy' }}
    permissions:
      # needs write permission to push the docs to gh-pages
      contents: write
    # Use the "reusable workflow" from the hyperspy organisation
    uses: hyperspy/.github/.github/workflows/push_doc.yml@main
